#for the prod env
version: "3.7"
services:

  nginx:
    build: ./nginx
    ports:
      - 1337:80
    depends_on:
      - web
  db:
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"

  web:
    command: gunicorn realestate.wsgi:application --bind 0.0.0.0:8000
    # command: >
    #   sh -c 'python manage.py wait_for_db &&
    #          python manage.py migrate &&
    #          python manage.py runserver 0.0.0.0:8000'
    volumes:
      - .:/usr/src/app/
    # remove the ports and add expose for prod so the 8000 only expose to the internal sevice
    expose:
      - 8000
    env_file:
      - .env
    environment:
      - DB_HOST=db
      - DB_NAME=${POSTGRES_DB}
      - DB_USER=${POSTGRES_USER}
      - DB_PASS=${POSTGRES_PASSWORD}
