#python manage.py wait_for_db &&
version: "3.7"
services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=realestate
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=zhang199711
  web:
    build: .
    command: >
      sh -c ' 
             python manage.py runserver 0.0.0.0:8000'
    volumes:
      - .:/usr/src/code/
    ports:
      - 8000:8000
    env_file:
      - ./.env
    depends_on:
      - db