#for the prod env
version: "3.7"
services:

  db:
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
     
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"

  web:
    command: >
      sh -c 'python manage.py wait_for_db &&
             python manage.py migrate &&
             gunicorn realestate.wsgi:application --bind 0.0.0.0:8000'
      
    volumes:
      # after the colon is the path in container not local project
      - static_content:/app/static/
      - media_content:/app/media/
    # remove the ports and add expose for prod so the 8000 only expose to the internal sevice
    expose:
      - 8000
    env_file:
      - .env
    environment:
      - DB_HOST=db
      - DB_NAME=${POSTGRES_DB}
      - DB_USER=${POSTGRES_USER}
      - DB_PASS=${POSTGRES_PASSWORD}

  nginx:
    image: nginx:1.13
    ports:
      - 8000:80
    volumes:
      - ./config/nginx/conf.d:/etc/nginx/conf.d
      - static_content:/static/
      - media_content:/media/
    depends_on:
      - web
